config/routes.rb
Rails.application.routes.draw do
  root "landings#show"

  resources :blog_posts, only:[:index]
  resources :projects, only:[:index]
  resources :users, only:[:show]

end

app/models/blog_post.rb
class BlogPost < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :blog_posts
  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  def index
    @user = User.first
    @blog_posts = @user.blog_posts
  end
end

app/controllers/landings_controller.rb
class LandingsController < ApplicationController
  def show
    @user = User.first
    @blog_posts = @user.blog_posts
    @projects = @user.projects
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @user = User.first
    @projects = @user.projects
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/index.html.erb
<script type="text/javascript">
  $(document).ready(function() {
    $(".posts").click(function(event) {
      event.preventDefault();
      var text_name = "#text" + $(this).attr("id");
      $(text_name).toggleClass("open");
    });
  });
</script>

<header class="nav_header">
  <%= link_to("Home", root_path) %> - <%= link_to("About Me", user_path(@user.id)) %> - <%= link_to("Projects", projects_path) %>
  <div class ="top_line"></div>
</header>

<h3 id="blog_head">My Blog</h3>

<div id="blog_posts">
  <ul>
    <% @blog_posts.each do |post| %>
      <li class="posts" id=<%=post.id %>><a href="/">Blog Post <%= post.id%>: <%= post.title %></a></li>
      <p class="blog_text" id=text<%=post.id %>><%= post.text %></p>
    <% end %>
</ul>
</div>

<footer class="nav_footer">
  <div class="bot_line"></div>
  <a href="mailto:nick.brown2014@gmail.com?Subject=Hello" target="_top"><img id="mail_nav" src="https://raw.githubusercontent.com/nick-brown2014/nick-brown2014.github.io/master/blog-posts/imgs/email_logo.gif"></a>
  <a href="https://github.com/nick-brown2014" target="_blank"><img src="https://raw.githubusercontent.com/nick-brown2014/nick-brown2014.github.io/master/blog-posts/imgs/github-clear.png"></a>
  <a href="https://www.linkedin.com/pub/nick-brown/88/178/b62/" target="_blank"><img id="link_nav" src="https://raw.githubusercontent.com/nick-brown2014/nick-brown2014.github.io/master/blog-posts/imgs/linkedin_png.png"></a>
  <a href="https://twitter.com/SunnyBrownCC" target="_blank"><img src="https://raw.githubusercontent.com/nick-brown2014/nick-brown2014.github.io/master/blog-posts/imgs/twitter-bird.png"></a>
</footer>

app/views/landings/show.html.erb
<style>
* {
    box-sizing: border-box;
    font-family: "Courier";
}

body {
    position: relative;
    display: block;
    overflow: auto;
    background: url("https://github.com/nick-brown2014/nick-brown2014.github.io/blob/master/blog-posts/imgs/StickNickTree2.png?raw=true") no-repeat center center;
    background-size: auto 100%;
}

.container {
    position: relative;
    height: 650px;
    width: 600px;
    margin: auto;
}

#about {
    position: absolute;
    top: 10%;
    left: 20%;
    font-size: 1em;
}

#about img {
    height: 70px;
    width: auto;
}

#blog {
    position: absolute;
    top: 20%;
    left: 47%;
    font-size: 1em;
}

#blog img {
    height: 70px;
    width: auto;
}

#projects {
    position: absolute;
    top: 33%;
    left: 13%;
}

#projects img {
    height: 80px;
    width: auto;
}

#page-title {
    position: absolute;
    top: 49%;
    left: 31%;
    font-size: 1.75em;
    font-family: "Courier";
}

h6 {
    position: absolute;
    top: 52%;
    left: 36%;
    font-size: 0.8em;
}

.nav_image {
    border: 1px solid black;
    height: 42px;
    width: auto;
}

#twitter {
    width: 50px;
    heigth: auto;
    position: absolute;
    top: 31%;
    left: 66%;
}

#linkedin {
    width: 42px;
    heigth: auto;
    position: absolute;
    top: 38%;
    left: 60.5%;
}

#github {
    width: 42px;
    heigth: auto;
    position: absolute;
    top: 39%;
    left: 68%;
}

#email {
    width: 28px;
    heigth: auto;
    position: absolute;
    top: 28%;
    left: 83.5%;
}

#prof_pic {
    width: 150px;
    height: auto;
    position: absolute;
    top: 68%;
    left: 10%;
}

.foot {
    width: 90%;
    margin-left: 5%;
    margin-right: 5%;
}

.foot p{
    max-width: 600px;
    margin: auto;
}

footer {
    height: 100%;
}

#foot-about {
    display: block;
    position: absolute;
    bottom: -150px;
    height: 150px;
}

#foot-about h1 {
    text-align: center;
}

#foot-about h1 a {
    text-decoration: none;
    color: black;
}

#foot-about h1 a:hover {
    color: white;
    -webkit-text-stroke: 1px black;
}

#foot-about p {
    color: black;
    text-align: center;
}

#foot-blog {
    display: block;
    position: absolute;
    bottom: -300px;
    height: 150px;
}

#foot-blog h1 {
    text-align: center;
}

#foot-blog h1 a {
    text-decoration: none;
    color: black;
}

#foot-blog h1 a:hover {
    color: white;
    -webkit-text-stroke: 1px black;
}

#foot-blog p {
    color: black;
    text-align: center;
}

#foot-projects {
    display: block;
    position: absolute;
    bottom: -440px;
    height: 150px;
}

#foot-projects h1 {
    text-align: center;
}

#foot-projects h1 a {
    text-decoration: none;
    color: black;
}

#foot-projects h1 a:hover {
    color: white;
    -webkit-text-stroke: 1px black;
}

#foot-projects p {
    color: black;
    text-align: center;
}

.nav_footer img {
  width: 60px;
  height: auto;
  margin-right: -5px;
}

#mail_nav {
  width: 80px;
  height: auto;
}

#link_nav {
  margin-right: 5px;
}

.nav_footer {
  text-align: center;
  position: absolute;
  bottom: -540px;
  width: 100%;
}

.bot_line {
  margin-top: 15px;
  margin-bottom: 10px;
  border: 1px solid black;
  width: 70%;
  max-width: 650px;
  margin: auto;
}

#about-blog-line {
    position: absolute;
    bottom: -150px;
    left: 5%;
}

#blog-projects-line {
    position: absolute;
    bottom: -300px;
    left: 5%;
}

</style>

<script type="text/javascript">
    $(document).ready(function(){
        function moveLeft(object, speed) {
            $(object).animate({
                "left": "-=50px"
            }, speed);
        };
        function moveRight(object, speed) {
            $(object).animate({
                "left": "+=50px"
            }, speed);
        };
        for (i = 0; i < 1000; i++) {
            moveLeft("#blog", 10000);
            moveRight("#blog", 10000);
            moveRight("#projects", 15000);
            moveLeft("#projects", 15000);
            moveRight("#about", 5000);
            moveLeft("#about", 5000);
        };
        function shake(object) {
            $(object).animate({"left": "-=2px"},100);
            $(object).animate({"left": "+=4px"},100);
            $(object).animate({"left": "-=2px"},100);
        };
        $("#twitter").hover(function(){
            shake($(this));
        });
        $("#linkedin").hover(function(){
            shake($(this));
        });
        $("#github").hover(function(){
            shake($(this));
        });
        $("#email").hover(function(){
            shake($(this));
        });
    });
</script>
<%= favicon_link_tag %>
<body>
    <div class="container">
        <div id="blog"><a href="/blog_posts"><img src="https://github.com/nick-brown2014/nick-brown2014.github.io/blob/master/blog-posts/imgs/blog.png?raw=true"></a></div>
        <div id="projects"><a href="/projects"><img src="https://github.com/nick-brown2014/nick-brown2014.github.io/blob/master/blog-posts/imgs/projects.png?raw=true"></a></div>
        <div id="about"><a href="/users/1"><img src="https://github.com/nick-brown2014/nick-brown2014.github.io/blob/master/blog-posts/imgs/about-me.png?raw=true"></a></div>
        <div>
            <a href ="https://twitter.com/SunnyBrownCC" target="_blank"><img id="twitter" src="https://raw.githubusercontent.com/nick-brown2014/nick-brown2014.github.io/master/blog-posts/imgs/twitter-clear.png"/></a>
        </div>
        <a href ="https://www.linkedin.com/pub/nick-brown/88/178/b62/" target="_blank"><img id="linkedin" src="https://raw.githubusercontent.com/nick-brown2014/nick-brown2014.github.io/master/blog-posts/imgs/linkedin_png.png" /></a>
        <a href ="https://github.com/nick-brown2014" target="_blank"><img id="github" src="https://raw.githubusercontent.com/nick-brown2014/nick-brown2014.github.io/master/blog-posts/imgs/github-clear.png" /></a>
        <a href="mailto:nick.brown2014@gmail.com?Subject=Hello" target="_top"><img id="email" src="http://www.myunitrade.com/assets/email-e61b80503c209b4bd584a0e70631a8fd.png" /></a>
        <header>
          <h1 id = "page-title">Nick Brown</h1>
          <h6>Web Developer</h6>
        </header>
        <img id="prof_pic" src="https://raw.githubusercontent.com/nick-brown2014/nick-brown2014.github.io/master/blog-posts/imgs/StickNick.png" />
    </div>
    <footer>
        <div class="foot" id="foot-about">
            <h1><%= link_to("About Me", user_path(@user.id)) %></h1>
            <p>I am a Chicago based freelance developer who cares about building websites that are modern, responsive and above all, unique. Apart from helping you and your brand build the web presence you need, I am commmited to transparency and honesty in my work.</p>
        </div>
        <div class="foot" id="foot-blog">
            <h1><%= link_to("Blog Posts", blog_posts_path) %></h1>
            <p>A bunch of blog posts that I wrote about programming while I didn't know anything about it!  At least they're kind of entertaining...</p>
        </div>
        <div  class="foot" id="foot-projects">
            <h1><%= link_to("Projects", projects_path) %></h1>
            <p>These are some of the projects that I have worked since I started programming.  Check back on this section often as I intend to keep it growing!</p>
        </div>
    </footer>
    <div class="nav_footer">
      <div class="bot_line"></div>
      <a href="mailto:nick.brown2014@gmail.com?Subject=Hello" target="_top"><img id="mail_nav" src="https://raw.githubusercontent.com/nick-brown2014/nick-brown2014.github.io/master/blog-posts/imgs/email_logo.gif"></a>
      <a href="https://github.com/nick-brown2014" target="_blank"><img src="https://raw.githubusercontent.com/nick-brown2014/nick-brown2014.github.io/master/blog-posts/imgs/github-clear.png"></a>
      <a href="https://www.linkedin.com/pub/nick-brown/88/178/b62/" target="_blank"><img id="link_nav" src="https://raw.githubusercontent.com/nick-brown2014/nick-brown2014.github.io/master/blog-posts/imgs/linkedin_png.png"></a>
      <a href="https://twitter.com/SunnyBrownCC" target="_blank"><img src="https://raw.githubusercontent.com/nick-brown2014/nick-brown2014.github.io/master/blog-posts/imgs/twitter-bird.png"></a>
    </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NickBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/index.html.erb
<header class="nav_header">
  <%= link_to("Home", root_path) %> - <%= link_to("Blog Posts", blog_posts_path) %> - <%= link_to("About Me", user_path(@user.id)) %>
  <div class ="top_line"></div>
</header>

<div id="projects_list">
  <ul>
    <% @projects.each do |project| %>
      <h2><%= project.title %></h2>
      <li class="project_text"><%= project.description %></li>
      <p>Feel free to check it out at <%= link_to(project.link, project.link, target: "_blank") %></p>
    <% end %>
  </ul>
</div>

<footer class="nav_footer">
  <div class="bot_line"></div>
  <a href="mailto:nick.brown2014@gmail.com?Subject=Hello" target="_top"><img id="mail_nav" src="https://raw.githubusercontent.com/nick-brown2014/nick-brown2014.github.io/master/blog-posts/imgs/email_logo.gif"></a>
  <a href="https://github.com/nick-brown2014" target="_blank"><img src="https://raw.githubusercontent.com/nick-brown2014/nick-brown2014.github.io/master/blog-posts/imgs/github-clear.png"></a>
  <a href="https://www.linkedin.com/pub/nick-brown/88/178/b62/" target="_blank"><img id="link_nav" src="https://raw.githubusercontent.com/nick-brown2014/nick-brown2014.github.io/master/blog-posts/imgs/linkedin_png.png"></a>
  <a href="https://twitter.com/SunnyBrownCC" target="_blank"><img src="https://raw.githubusercontent.com/nick-brown2014/nick-brown2014.github.io/master/blog-posts/imgs/twitter-bird.png"></a>
</footer>

app/views/users/show.html.erb
<header class="nav_header">
  <%= link_to("Home", root_path) %> - <%= link_to("Blog Posts", blog_posts_path) %> - <%= link_to("Projects", projects_path) %>
  <div class ="top_line"></div>
</header>

<h3 id="about_head">About Me</h3>

<p id="about_text">Hello and welcome to my website!  It has recently been reformatted with Ruby on Rails, and I hope you've enjoyed it.<br><br>My name is Nick, I am a 22 year old Creative Writing Major and Web Developer living and looking for full-time opportunities in Chicago.<br><br>If you would like to get in touch with me feel free to find me through email or linked-in, I'm sure I would love to hear from you.  In the meantime, check out some of the projects I've worked on any of the blog posts that I wrote while I was preparing to study programming at Dev Bootcamp.</p>

<footer class="nav_footer">
  <div class="bot_line"></div>
  <a href="mailto:nick.brown2014@gmail.com?Subject=Hello" target="_top"><img id="mail_nav" src="https://raw.githubusercontent.com/nick-brown2014/nick-brown2014.github.io/master/blog-posts/imgs/email_logo.gif"></a>
  <a href="https://github.com/nick-brown2014" target="_blank"><img src="https://raw.githubusercontent.com/nick-brown2014/nick-brown2014.github.io/master/blog-posts/imgs/github-clear.png"></a>
  <a href="https://www.linkedin.com/pub/nick-brown/88/178/b62/" target="_blank"><img id="link_nav" src="https://raw.githubusercontent.com/nick-brown2014/nick-brown2014.github.io/master/blog-posts/imgs/linkedin_png.png"></a>
  <a href="https://twitter.com/SunnyBrownCC" target="_blank"><img src="https://raw.githubusercontent.com/nick-brown2014/nick-brown2014.github.io/master/blog-posts/imgs/twitter-bird.png"></a>
</footer>